sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: aRSy0y9bftOhgiXlKvuX2gtE2syJwAJWvBUKnr8puySGxVtFIeWLSwb3TOeLSiUzrz1CUmNYu2ZP4nA1+HmWX0yzxBpjMZoQnvhjCpXiowAGpp8W+5B9mETVbInzHaSLgNSfLB6YE+eBk7HOqz+Qpdq5JU0kaO9N9ae/Uaf0nQ8Mme5BCidLeTuF9izZ4p5mOfc9xiztldltZx7wKfEgYTVIojFnNuY5D2BYaurxXVT8efUmzW5HCUWzooo4rx7ZbhmUu2KMD/25PW9c0eEvrP/YiCNcTVv8bDKhY5/+Xhu8raI786qdUW0b8GIKsCw9rbrebps6rGZCIFi2PbyGaga2Pp10ddpS0d6k+TX4Kri4REN7sUYJITxsZ1IbE0Fj7vM7VY108H9bGQJFA7B280QopI4uG1390dXfaPs6iEJd531E5Lo9gxzFnVCQwldy6OZXOfXvE1mgnWmegCqQPHwgG4tMuxMstYMZ0BL/r5eav7ZeOs3p/qEQEGlIAjR/Oy9lfnoavPkvZJNptkcnR4pBOkgIlx7YXn5RdQRRYmvjacZcYvFjOcTNAENXKuR0XE0smzO/WlQCaBY4MxN4IVMTY5G+6lV30YSRCin2IRk2OiCOSwhhA5hriYSHJCNTpaetgVOfu7pZID4J+9vLJBSosRv3QSSBm5GFEB0N9Ik=
  - secure: oKKYbN3DlFYKHykBq0UWDSxlx+egbVUUQ6kcY7ZF2YAhR5ARVyIZnWpu5bvJsjHsxg1PHxqViHxOxroSxt/ulI0QmHB5hIu4Ar+ItVqqcLReCsB+eJOS0DVUrFH5nqMhz8uAe2PDdQ9joszKsnDCg1Ko4xWa6Y4LiOOHuco5g/LPUV382fEZ+f5XhY8f473enhJkmyGUjrR2u1eHja6H3p5jNqT90soM+ARpFYsUaVwoGqzkOaZIs1MV9ucH8beeCzTerLUpFp7vhkyTWNQN2WhDZWcN4Bt1YNldOukNUvNmglA+sPOLG8dbBaxUbENbA850B1tMp+FAx1ZawLr/ENf6d3zR5ha0y+8L7jebuZ8BcxkFF2sq62hDUwoHgjspBnmE/Lkxh0bQjwh8ePLdK+3EARdzuYKAvQEjv+1/BIiJVfBKIEZboNme6oWJ7dG/P1VW5aEdQf3p+VKWeQai2xgQnOaWngINBCYPbBKuqkt0peBpyzvLp/t5rehM1646IWSM8+7R5O5YzrnkwxJ/s6C34nTjDRQpp4cNHJT19MZWEGDaU94wmSv1n+rdEpAermVk8ZZ3Qvpl2ZvAJH7EurLeANBRfp6FtycXmwqjAHEwtkwOaSw4qMLKxRn+B+EgtE7noVt24BYuEwJeYYHpGL/xmHOyqDljpP1uD2HeKu8=
before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password" -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
